#ifndef CONTROLLERBACKEND_GLOBAL_H
#define CONTROLLERBACKEND_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CONTROLLERBACKEND_LIBRARY)
#  define CONTROLLERBACKEND_EXPORT Q_DECL_EXPORT
#else
#  define CONTROLLERBACKEND_EXPORT Q_DECL_IMPORT
#endif

#endif // CONTROLLERBACKEND_GLOBAL_H
